# Generated by Django 3.2.7 on 2022-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=128, verbose_name='Почта')),
                ('motor', models.IntegerField(verbose_name='Мощность двигателя')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('appointment', models.CharField(max_length=128, verbose_name='Назначение')),
                ('provider', models.CharField(max_length=128, verbose_name='Постовщик')),
                ('brand', models.CharField(max_length=128, verbose_name='Марка')),
            ],
        ),
    ]
