# Generated by Django 3.2.7 on 2022-01-15 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShow_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=128, verbose_name='Почта')),
                ('motor', models.IntegerField(verbose_name='Мощность двигателя')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('brand', models.CharField(max_length=128, verbose_name='Марка')),
                ('appointment', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), size=None), size=None)),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), size=None), size=None)),
            ],
        ),
    ]
