# Generated by Django 3.2.7 on 2022-01-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoshow',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='autoshow',
            name='provider',
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_provider', models.CharField(max_length=128, verbose_name='Постовщик')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_1.autoshow', verbose_name='provider_auto_id')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_appoint', models.CharField(max_length=128, verbose_name='Назначение')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_1.autoshow', verbose_name='appoint_auto_id')),
            ],
        ),
    ]
